# Generated by Django 3.1.4 on 2021-05-11 23:56

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SNA', 'Закуски'), ('HOT', 'Горяие блюда'), ('DRI', 'Напитки'), ('SWE', 'Десерты'), ('SAL', 'Салаты')], default='HOT', max_length=3)),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('description', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Описание блюда')),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=project.models.generate_imageset_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dishes', models.CharField(default='Предварительный заказ отсутствует.', max_length=255, verbose_name='Блюда')),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('seats_num', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons_num', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Бронирование')),
                ('booked_at', models.DateTimeField(default=datetime.datetime.now)),
                ('duration', models.DurationField(default=datetime.timedelta(0, 1200))),
                ('status', models.CharField(choices=[('WA', 'В ожидании'), ('AC', 'Подтверждено'), ('RE', 'Отклонено')], default='WA', max_length=2)),
                ('closed', models.BooleanField(default=False, verbose_name='Бронь закрыта?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.preorder', verbose_name='Предзаказ')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.table', verbose_name='Стол')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший бронь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
