# Generated by Django 3.2.3 on 2021-06-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210515_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('SNA', 'Закуски'), ('HOT', 'Горяие блюда'), ('DRI', 'Напитки'), ('SWE', 'Торты'), ('SAL', 'Салаты'), ('BAO', 'Бао'), ('WAT', 'Горячие кофейные напитки'), ('PST', 'Паста'), ('PIZ', 'Пицца'), ('SOU', 'Супы')], default='HOT', max_length=3),
        ),
    ]
